In [1]:
import pandas as pd
import numpy as np
import waterfall_chart

In [2]:
# pip install waterfallcharts
# pip install openpyxl

In [3]:
import pandas as pd
df = pd.read_excel(r"C:\Users\kelvin\Downloads\Sales and Payment Plans Data.xlsx")
df

,Created At Date,Payment Plan Name,Product Sub Category,Product Type,Currency Name,Product Price,Deposit,Daily Top Up,Loan Duration,Total Top Ups,Brand,Masterbrand,Model,Plan Type,Product Category,Variant,Mart Payment Plan ID,Payment Plan Status
0,2023-04-20,"MK 600 24"" TV v21 Staff",M-KOPA 600,Solar TV,KES,64199,2999.0,90.0,680.0,61200.0,M-KOPA,Solar,M-KOPA 600,Acquisition,MK TV,"24"" TV",4319,Active
1,2023-04-20,"MK 6000C 32"" TV v3 Staff",M-KOPA 6000,Solar TV,KES,86499,6499.0,100.0,800.0,80000.0,M-KOPA,Solar,M-KOPA 6000,Acquisition,MK TV,"32"" TV",4318,New
2,2023-02-08,"MK 600 24"" TV v24 Non-Locking HRA",M-KOPA 600,Solar TV,KES,81999,5999.0,100.0,760.0,76000.0,M-KOPA,Solar,M-KOPA 600,Acquisition,MK TV,"24"" TV",4077,Closed
3,2023-02-08,MK 6 v11 HRA,M-KOPA 6,Lights,KES,23999,999.0,50.0,460.0,23000.0,M-KOPA,Solar,M-KOPA 6,Acquisition,MK Classic,4 lights,4088,Active
4,2023-02-08,"MK 6000 32"" TV v24 Non Locking HRA",M-KOPA 6000,Solar TV,KES,116199,6999.0,130.0,840.0,109200.0,M-KOPA,Solar,M-KOPA 6000,Acquisition,MK TV,"32"" TV",4102,Closed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,2015-12-04,M-KOPA 4 Staff,M-KOPA 4,Lights,KES,15275,2500.0,35.0,365.0,12775.0,M-KOPA,Solar,M-KOPA 4,Acquisition,MK Classic,3 lights,93,Active
484,2015-12-04,M-KOPA 4 Demo,M-KOPA 4,Lights,KES,15750,750.0,25.0,600.0,15000.0,M-KOPA,Solar,M-KOPA 4,Acquisition,MK Classic,3 lights,92,Closed
485,2015-12-01,M-KOPA 4 Cash v1,M-KOPA 4,Lights,KES,17750,NaN,NaN,NaN,NaN,M-KOPA,Solar,M-KOPA 4,Acquisition,MK Classic,3 lights,90,Closed
486,2015-12-01,M-KOPA 4 v2,M-KOPA 4,Lights,KES,21750,3500.0,50.0,365.0,18250.0,M-KOPA,Solar,M-KOPA 4,Acquisition,MK Classic,3 lights,91,Closed
487,2015-09-17,M-KOPA 4 v1,M-KOPA 4,Lights,KES,21249,2999.0,50.0,365.0,18250.0,M-KOPA,Solar,M-KOPA 4,Acquisition,MK Classic,3 lights,87,Closed

In [4]:
temp1 = pd.DataFrame(df.groupby(['Product Sub Category']).agg({'Product Price':'sum'}))
temp = temp1.head(200)

In [5]:
x=temp.index
y=temp['Product Price'].values
print(x)
print(y)

Index(['M-KOPA +400', 'M-KOPA +400 Zuku', 'M-KOPA +500', 'M-KOPA +500 Zuku',
       'M-KOPA +6', 'M-KOPA +600', 'M-KOPA +600 Grid', 'M-KOPA +600 Zuku',
       'M-KOPA +6000', 'M-KOPA +6000 Grid', 'M-KOPA +6000 Zuku',
       'M-KOPA +Fridge 100L', 'M-KOPA +Fridge 47L', 'M-KOPA +TV',
       'M-KOPA 3 Starter', 'M-KOPA 4', 'M-KOPA 4 Starter', 'M-KOPA 400',
       'M-KOPA 400 Starter', 'M-KOPA 400 Zuku', 'M-KOPA 5', 'M-KOPA 5 Starter',
       'M-KOPA 500', 'M-KOPA 500 Zuku', 'M-KOPA 6', 'M-KOPA 600',
       'M-KOPA 600 Grid', 'M-KOPA 600 Zuku', 'M-KOPA 6000', 'M-KOPA 6000 Grid',
       'M-KOPA 6000 Zuku', 'M-KOPA 60000', 'M-KOPA Fan', 'M-KOPA Fridge 100L',
       'M-KOPA Fridge 47L', 'Starter Upgrade Pack'],
      dtype='object', name='Product Sub Category')
[ 952000  467451 1717626  569500   66999 1567193   63000  767700 1465487
  143999  633994 1160993  306498 1253500  109697  582415  151694 2000214
   94998 1080911  274990   13999  730437  437344  423231 2312766  219496
  775841 4127866  562994 1200689  569997     160 1389490  205998   45498]

In [6]:
z = plt.figure()
plt.rcParams['figure.figsize'] =(10,6)
plt.rcParams['figure.facecolor'] ='yellow'
waterfall_chart.plot(x,y,net_label='Total',rotation_value=90)
plt.xticks(rotation=90)
plt.show();

NameError: name 'plt' is not defined

In [ ]:
import matplotlib.pyplot as plt
z = plt.figure()
plt.rcParams['figure.figsize'] =(10,6)
plt.rcParams['figure.facecolor'] ='yellow'
waterfall_chart.plot(x,y)
plt.xticks(rotation=90)
plt.show();

In [ ]:
z = plt.figure()
plt.rcParams['figure.figsize'] =(10,6)
plt.rcParams['figure.facecolor'] ='yellow'
waterfall_chart.plot(x,y,net_label='Total',rotation_value=90,sorted_value=True)
plt.xticks(rotation=90)
plt.show();